[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"

# Cache the API responses
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
